### ISSUE TITLE
rocm-smi --setpoweroverdrive fails to find or use sysfs correctly

### ISSUE THREAD

**Issue by hairetikos** [RadeonOpenCompute/ROC-smi#66]
**invoking rocm-smi --setpoweroverdrive 100:**

```
Do you accept these terms? [y/N] y
Traceback (most recent call last):
  File "/usr/bin/rocm-smi", line 1910, in <module>
    setPowerOverDrive(deviceList, args.setpoweroverdrive, args.autorespond)
  File "/usr/bin/rocm-smi", line 1396, in setPowerOverDrive
    power_cap_path = getFilePath(device, 'power1_cap')
  File "/usr/bin/rocm-smi", line 130, in getFilePath
    pathDict = valuePaths[key]
KeyError: 'power1_cap'
root@amd://# 
```

**this does works:**
`echo 100000000 > /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:00.0/0000:03:00.0/hwmon/hwmon1/power1_cap`

**Ubuntu 18.04 + CentOS 7**

strangely, `rocm-smi --setpoweroverdrive` does work in an ubuntu virtual machine with AMD GPUs i have, but i am running a 5.x kernel on the host with custom kernel, maybe i changed something which is required, idk.

**Comment by jlgreathouse** [comment]
What does "Ubuntu 18.04 + CentOS 7" mean?

What GPUs do you have on your system? What "custom kernel" do you mean? What software and version of everything are you using? Do you have the OverDrive bit enabled in your driver's ppfeaturemask?

Could you run the following and show the output?
```bash
for i in `ls -1 /sys/class/hwmon/`; do echo ${i}; cat /sys/class/hwmon/${i}/device/vendor; cat /sys/class/hwmon/${i}/device/device; done
```

For any of the hwmon directories (`hwmon#`) that show "0x1002" for the output of the `vendor` file, could you show me the contents of `/sys/class/hwmon/hwmon#/`?

**Comment by hairetikos** [comment]
all GPU are RX580, a mix of ASUS 4GB Dual OC & PowerColor Red Dragon 8GB & 1x XFX 8GB

on ubuntu server 18.04.2 VM the command works ok (debian stretch w/custom Linux 5.x as host)
custom 5.x kernel = compiled from source after changing a lot of things via make menuconfig

CentOS 7 running on bare metal it has the issue
now on ubuntu 18.04.2 bare metal w/same issue

`amdgpu.ppfeaturemask=0xffffffff` is enabled on all machines

**ubuntu 18.04.2 bare metal (7 ASUS/PowerColor/XFX GPU):**
- Linux 4.15.0-48-generic #51-Ubuntu
- kernel options:  `amdgpu.vm_fragment_size=9 amdgpu.ppfeaturemask=0xffffffff`
- amdgpu-pro-19.10-785425-ubuntu-18.04 `--opencl=legacy,pal --headless`
- latest rocm-smi from git master branch

this machine is using a 1x to 4x PCIe adapter switch to fit in extra GPUs (PCIE-EUX1-04 VER.002)

**output:**
```
hwmon0
cat: /sys/class/hwmon/hwmon0/device/vendor: No such file or directory
cat: /sys/class/hwmon/hwmon0/device/device: No such file or directory
hwmon1
0x1002
0x67df
hwmon2
0x1002
0x67df
hwmon3
0x1002
0x67df
hwmon4
0x1002
0x67df
hwmon5
0x1002
0x67df
hwmon6
0x1002
0x67df
hwmon7
0x1002
0x67df
hwmon8
```
**/sys/class/hwmon symlinks:**
```
hwmon0 -> ../../devices/virtual/hwmon/hwmon0
hwmon1 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:01.0/0000:03:00.0/hwmon/hwmon1
hwmon2 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:05.0/0000:05:00.0/hwmon/hwmon2
hwmon3 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/0000:02:07.0/0000:06:00.0/hwmon/hwmon3
hwmon4 -> ../../devices/pci0000:00/0000:00:1b.0/0000:07:00.0/hwmon/hwmon4
hwmon5 -> ../../devices/pci0000:00/0000:00:1b.5/0000:08:00.0/hwmon/hwmon5
hwmon6 -> ../../devices/pci0000:00/0000:00:1c.6/0000:0a:00.0/hwmon/hwmon6
hwmon7 -> ../../devices/pci0000:00/0000:00:1c.7/0000:0b:00.0/hwmon/hwmon7
hwmon8 -> ../../devices/platform/coretemp.0/hwmon/hwmon8
```
**/sys/class/hwmon1:**
```
device -> ../../../0000:03:00.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
freq1_input
freq1_label
freq2_input
freq2_label
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**/sys/class/hwmon2:**
```
device -> ../../../0000:05:00.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
freq1_input
freq1_label
freq2_input
freq2_label
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**/sys/class/hwmon3:**
```
device -> ../../../0000:06:00.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
freq1_input
freq1_label
freq2_input
freq2_label
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**/sys/class/hwmon4:**
```
device -> ../../../0000:07:00.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
freq1_input
freq1_label
freq2_input
freq2_label
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**/sys/class/hwmon5:**
```
device -> ../../../0000:08:00.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
freq1_input
freq1_label
freq2_input
freq2_label
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**/sys/class/hwmon6:**
```
device -> ../../../0000:0a:00.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
freq1_input
freq1_label
freq2_input
freq2_label
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**/sys/class/hwmon7:**
```
device -> ../../../0000:0b:00.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
freq1_input
freq1_label
freq2_input
freq2_label
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**ubuntu 18.04.2 VM (2 ASUS GPU):**
- Linux 4.15.0-47-generic #50-Ubuntu
- kernel options:  `amdgpu.vm_fragment_size=9 amdgpu.ppfeaturemask=0xffffffff`
- amdgpu-pro-18.50-756341-ubuntu-18.04 `--opencl=legacy,pal --headless`
- latest rocm-smi from git master branch

**output:**
```
hwmon0
0x1002
0x67df
hwmon1
0x1002
0x67df
```
**/sys/class/hwmon symlinks:**
```
hwmon0 -> ../../devices/pci0000:00/0000:00:02.0/hwmon/hwmon0
hwmon1 -> ../../devices/pci0000:00/0000:00:0a.0/hwmon/hwmon1
```
**/sys/class/hwmon/hwmon0:**
```
device -> ../../../0000:00:02.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```
**/sys/class/hwmon/hwmon1:**
```
device -> ../../../0000:00:0a.0
fan1_enable
fan1_input
fan1_max
fan1_min
fan1_target
in0_input
in0_label
name
power
power1_average
power1_cap
power1_cap_max
power1_cap_min
pwm1
pwm1_enable
pwm1_max
pwm1_min
subsystem -> ../../../../../class/hwmon
temp1_crit
temp1_crit_hyst
temp1_input
uevent
```

**Comment by jlgreathouse** [comment]
Ah, I think this problem was pointed out in this PR, and I now understand what was going on: https://github.com/RadeonOpenCompute/ROC-smi/pull/63

Could you try making the change in that PR to your own local rocm-smi Python script and see if it fixes the issue for you?

**Comment by hairetikos** [comment]
it works!
