### ISSUE TITLE
Could not change ranges of sclk and mclk.

### ISSUE THREAD

**Issue by shiest** [RadeonOpenCompute/ROC-smi#91]
I tried to change MCLK. but it was failed.

```
rig01% rocm-smi --setmrange 1 915


========================ROCm System Management Interface========================
Traceback (most recent call last):
  File "/opt/rocm-3.8.0/bin//rocm-smi", line 3071, in <module>
    setClockRange(deviceList, 'mclk', args.setmrange[0], args.setmrange[1], args.autorespond)
  File "/opt/rocm-3.8.0/bin//rocm-smi", line 2460, in setClockRange
    if clkType == 'sclk':
NameError: name 'clkType' is not defined
```

the bellow diff is the modified lines. could you merge it?

```
rig01% git diff 08ebdddbbd25b40d385b4b25876cca9727bfd033 b712b2bfdc373147648ef15f27d34262b74c8d84
diff --git a/rocm_smi.py b/rocm_smi.py
index 2c9a95d..050403b 100755
--- a/rocm_smi.py
+++ b/rocm_smi.py
@@ -2436,7 +2436,7 @@ def setVoltageCurve(deviceList, point, clk, volt, autoRespond):
             RETCODE = 1


-def setClockRange(deviceList, clktype, level, value, autoRespond):
+def setClockRange(deviceList, clkType, level, value, autoRespond):
     """ Set the range for the specified clktype in the PowerPlay table for a list of devices.

     Parameters:```

**Comment by kentrussell** [comment]
This was resolved in the 3.8 LIB-backed SMI. If you have any issues, please open a new issue at https://github.com/RadeonOpenCompute/rocm_smi_lib, as this repo will be deprecated and all SMI CLI functionality has moved over there. Thank you!
